### ISSUE TITLE
publication MQTT

### ISSUE THREAD

**Issue by yessiman81** [frtz13/Zero-Surplus-Dimmer#1]
Bonjour,
est il possible de rajouter une publication MQTT pour l'activer à distance.
merci pour votre projet, je l'utilise avec un shelly EM3 avec le cumul des 3 PH. ( url: /status  , et json: "total_power" ).
est ce normal que sur HA l'integration ne marche pas ?, car j'aime l'idée que ca fonctionne en direct sans système domotique.

**Comment by frtz13** [comment]
I am not quite sure to understand. integrate with Home Assistant, or not?
with this project, the idea was to use a minimum of infrastructure. No MQTT, no extra CPU. I have the impression that the ESP8266 already has quite some work to do, and did not want to push it further. I also compliled the project for a ESP32-C3 but before publishing it, I wanted to make it work in real life, which I did not so far (coming soon).
I published another project (https://github.com/frtz13/EnergyRouter/) which integrates with Home Assistant and works via MQTT.

**Comment by Nickous** [comment]
Hello
> je l'utilise avec un shelly EM3 avec le cumul des 3 PH. ( url: /status , et json: "total_power" )

What a good lead! I'm also with three-phase, EM3 and I was looking to do the sum of each phase. So thank you so much for opening my eyes with this url /status 

For HA integration, do you add `api:` in the yaml ?
