### ISSUE TITLE
error: 'class esphome::http_request::HttpRequestArduino'

### ISSUE THREAD

**Issue by Titom59** [frtz13/Zero-Surplus-Dimmer#2]
Hello, I have been using your esphome code for a while, without problem until now.
since the latest versions of esphome I have an error message during compilation.
there she is:

`/config/esphome/routeur-ecs.yaml: In lambda function:
/config/esphome/routeur-ecs.yaml:455:42: error: 'class esphome::http_request::HttpRequestArduino' has no member named 'get_string'
                           auto grid = id(http_request_shelly).get_string();`

sorry for my english, this is a google translation. I am French.

Thank you

**Comment by frtz13** [comment]
Hello. I'll have a look into this problem.

**Comment by frtz13** [comment]
... just published the update.

**Comment by Titom59** [comment]
Thanks you!
